# Use esta estrutura completa para evitar erros
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: 127.0.0.1
  username: postgres
  password: heitor2007 # <-- COLOQUE A SUA SENHA AQUI

development:
  <<: *default
  database: glysera_development # O nome da sua base de dados de desenvolvimento

test:
  <<: *default
  database: glysera_test # O nome da sua base de dados de teste
  
production:
  primary: &primary_production
    <<: *default
    database: glysera_production
    username: glysera
    password: <%= ENV["GLYSERA_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: glysera_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: glysera_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: glysera_production_cable
    migrations_paths: db/cable_migrate
